import { Meta, StoryObj } from '@storybook/react';
import { Button } from '@t3n/components';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof Button>;
export declare const button: Story;
export declare const small: Story;
export declare const big: Story;
export declare const secondary: Story;
export declare const inverse: Story;
export declare const highlight: Story;
export declare const loading: Story;
export declare const disabled: Story;
export declare const iconLeft: Story;
export declare const iconRight: Story;
