import { Meta, StoryObj } from '@storybook/react';
import { Checkbox } from '@t3n/components';
declare const meta: Meta<typeof Checkbox>;
export default meta;
type Story = StoryObj<typeof Checkbox>;
export declare const checkbox: Story;
export declare const disabled: Story;
export declare const checked: Story;
export declare const dark: Story;
export declare const withoutLabel: Story;
export declare const withFeedbackColor: Story;
