import { Story } from '@storybook/addon-docs';
import { Meta, StoryObj } from '@storybook/react';
import { IconButton } from '@t3n/components';
declare const meta: Meta<typeof IconButton>;
export default meta;
type Story = StoryObj<typeof IconButton>;
export declare const iconButton: Story;
export declare const expanded: Story;
export declare const loading: Story;
export declare const secondary: Story;
export declare const small: Story;
export declare const big: Story;
export declare const highlight: Story;
export declare const inverse: Story;
