import { Meta, StoryObj } from '@storybook/react';
import { Input } from '@t3n/components';
declare const meta: Meta<typeof Input>;
export default meta;
type Story = StoryObj<typeof Input>;
export declare const input: Story;
export declare const disabled: Story;
export declare const error: Story;
export declare const focused: Story;
export declare const withValue: Story;
export declare const withPlaceholder: Story;
