import { Meta, StoryObj } from '@storybook/react';
import { Link } from '@t3n/components';
declare const meta: Meta<typeof Link>;
export default meta;
type Story = StoryObj<typeof Link>;
export declare const link: Story;
export declare const disabled: Story;
export declare const small: Story;
export declare const highlight: Story;
export declare const inverse: Story;
