import { Meta, StoryObj } from '@storybook/react';
import { RadioButton } from '@t3n/components';
declare const meta: Meta<typeof RadioButton>;
export default meta;
type Story = StoryObj<typeof RadioButton>;
export declare const radioButton: Story;
export declare const disabled: Story;
export declare const checked: Story;
export declare const dark: Story;
export declare const withoutLabel: Story;
export declare const feedbackColor: Story;
