import { Meta, StoryObj } from '@storybook/react';
import { Textarea } from '@t3n/components';
declare const meta: Meta<typeof Textarea>;
export default meta;
type Story = StoryObj<typeof Textarea>;
export declare const textarea: Story;
export declare const withPlaceholder: Story;
export declare const disabled: Story;
export declare const focused: Story;
export declare const error: Story;
