import { Meta, StoryObj } from '@storybook/react';
import { Card } from '@t3n/components';
import { CardProps } from '@t3n/components/src/Card';
declare const meta: Meta<CardProps>;
export default meta;
type Story = StoryObj<typeof Card>;
export declare const card: Story;
export declare const linked: Story;
export declare const header: Story;
export declare const padding: Story;
export declare const splitted: Story;
