version: 2
registries:
  git-gitlab-yeebase-com:
    type: git
    url: https://gitlab.yeebase.com
    username: jsu
    password: "${{secrets.GIT_GITLAB_YEEBASE_COM_PASSWORD}}"
  git-github-com:
    type: git
    url: https://github.com
    username: x-access-token
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.2
    - 6.2.7
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.17.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.17.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.3.1
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
  - dependency-name: react-dev-utils
    versions:
    - 11.0.4
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.24.2
  - dependency-name: core-js
    versions:
    - 3.8.3
    - 3.9.1
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
  - dependency-name: eslint-webpack-plugin
    versions:
    - 2.4.3
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
  - dependency-name: chalk
    versions:
    - 4.1.0
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
  registries:
  - git-gitlab-yeebase-com
  - git-github-com
- package-ecosystem: npm
  directory: "/packages/components"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: react-spring
    versions:
    - 9.0.0
    - 9.1.0
  - dependency-name: framer-motion
    versions:
    - 3.10.0
    - 3.10.3
    - 3.3.0
    - 3.6.2
    - 3.6.4
    - 3.7.0
    - 4.0.0
    - 4.0.3
    - 4.1.2
    - 4.1.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: ts-jest
    versions:
    - 26.5.4
  - dependency-name: "@t3n/theme"
    versions:
    - 0.4.7
  - dependency-name: "@t3n/icons"
    versions:
    - 0.4.7
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
  - dependency-name: "@types/react-autosuggest"
    versions:
    - 10.1.3
  - dependency-name: "@t3n/configs"
    versions:
    - 0.4.5
  - dependency-name: jsdom
    versions:
    - 16.5.1
  - dependency-name: use-debounce
    versions:
    - 6.0.0
  - dependency-name: react-slick
    versions:
    - 0.28.0
    - 0.28.1
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  registries:
  - git-gitlab-yeebase-com
  - git-github-com
- package-ecosystem: npm
  directory: "/packages/configs"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  target-branch: master
  registries:
  - git-gitlab-yeebase-com
  - git-github-com
- package-ecosystem: npm
  directory: "/packages/icons"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.10
    - 9.0.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: "@types/prettier"
    versions:
    - 2.2.3
  - dependency-name: "@t3n/configs"
    versions:
    - 0.4.5
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  registries:
  - git-gitlab-yeebase-com
  - git-github-com
- package-ecosystem: npm
  directory: "/packages/storybook"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.2
    - 6.2.7
  - dependency-name: "@storybook/theming"
    versions:
    - 6.2.2
    - 6.2.7
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.2.2
    - 6.2.7
  - dependency-name: "@storybook/addons"
    versions:
    - 6.2.2
    - 6.2.7
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.2.2
    - 6.2.7
  - dependency-name: ts-loader
    versions:
    - 8.0.18
    - 8.1.0
  - dependency-name: "@t3n/components"
    versions:
    - 0.4.29
    - 0.4.30
  - dependency-name: "@t3n/theme"
    versions:
    - 0.4.7
  - dependency-name: "@t3n/icons"
    versions:
    - 0.4.7
  - dependency-name: "@t3n/configs"
    versions:
    - 0.4.5
  - dependency-name: "@types/react-autosuggest"
    versions:
    - 10.1.3
  - dependency-name: "@storybook/preset-create-react-app"
    versions:
    - 3.1.7
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
  - dependency-name: react-dev-utils
    versions:
    - 11.0.4
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: yup
    versions:
    - 0.32.9
  registries:
  - git-gitlab-yeebase-com
  - git-github-com
- package-ecosystem: npm
  directory: "/packages/theme"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: jsdom
    versions:
    - 16.5.1
    - 16.5.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: ts-jest
    versions:
    - 26.5.4
  - dependency-name: "@t3n/configs"
    versions:
    - 0.4.5
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  registries:
  - git-gitlab-yeebase-com
  - git-github-com
