version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
  - package_manager: "javascript"
    directory: "/packages/components"
    update_schedule: "weekly"
    target_branch: "master"
  - package_manager: "javascript"
    directory: "/packages/configs"
    update_schedule: "weekly"
    target_branch: "master"
  - package_manager: "javascript"
    directory: "/packages/icons"
    update_schedule: "weekly"
    target_branch: "master"
  - package_manager: "javascript"
    directory: "/packages/storybook"
    update_schedule: "weekly"
    target_branch: "master"
  - package_manager: "javascript"
    directory: "/packages/theme"
    update_schedule: "weekly"
    target_branch: "master"
