version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "stage"
  - package_manager: "javascript"
    directory: "/components"
    update_schedule: "weekly"
    target_branch: "stage"
  - package_manager: "javascript"
    directory: "/configs"
    update_schedule: "weekly"
    target_branch: "stage"
  - package_manager: "javascript"
    directory: "/icons"
    update_schedule: "weekly"
    target_branch: "stage"
  - package_manager: "javascript"
    directory: "/storybook"
    update_schedule: "weekly"
    target_branch: "stage"
  - package_manager: "javascript"
    directory: "/theme"
    update_schedule: "weekly"
    target_branch: "stage"
