export declare const redLight = "#f9423a";
export declare const red = "#d7322b";
export declare const black = "#000";
export declare const anthracite = "#2a2a2a";
export declare const grey = "#9b9b9b";
export declare const greyLight = "#e8e8e8";
export declare const greyLighter = "#f4f4f4";
export declare const white = "#fff";
export declare const brandColors: {
    redLight: string;
    red: string;
    black: string;
    anthracite: string;
    grey: string;
    greyLight: string;
    greyLighter: string;
    white: string;
};
export declare const comment = "#f9423a";
export declare const podcast = "#f9423a";
export declare const mail = "#9b9b9b";
export declare const twitter = "#5bc6f8";
export declare const facebook = "#6175b5";
export declare const google = "#d44132";
export declare const flipboard = "#f9261a";
export declare const pocket = "#EC4259";
export declare const instagram = "#d448c5";
export declare const linkedin = "#008cc9";
export declare const whatsapp = "#64d448";
export declare const xing = "#338383";
export declare const socialColors: {
    comment: string;
    podcast: string;
    mail: string;
    twitter: string;
    facebook: string;
    google: string;
    flipboard: string;
    pocket: string;
    instagram: string;
    linkedin: string;
    whatsapp: string;
    xing: string;
};
export declare const success = "#34e88f";
export declare const notice = "#9b9b9b";
export declare const warn = "#fbbe35";
export declare const error = "#ff7e00";
export declare const utilColors: {
    success: string;
    notice: string;
    warn: string;
    error: string;
};
export declare const background = "#fff";
export declare const backgroundInverse = "#2a2a2a";
export declare const backgroundLight = "#e8e8e8";
export declare const backgroundLighter = "#f4f4f4";
export declare const backgroundHighlight = "#f9423a";
export declare const backgroundColors: {
    primary: string;
    inverse: string;
    light: string;
    lighter: string;
    highlight: string;
};
declare const colors: {
    brand: {
        redLight: string;
        red: string;
        black: string;
        anthracite: string;
        grey: string;
        greyLight: string;
        greyLighter: string;
        white: string;
    };
    social: {
        comment: string;
        podcast: string;
        mail: string;
        twitter: string;
        facebook: string;
        google: string;
        flipboard: string;
        pocket: string;
        instagram: string;
        linkedin: string;
        whatsapp: string;
        xing: string;
    };
    util: {
        success: string;
        notice: string;
        warn: string;
        error: string;
    };
    background: {
        primary: string;
        inverse: string;
        light: string;
        lighter: string;
        highlight: string;
    };
};
export default colors;
