import { Meta, StoryObj } from '@storybook/react';
import { UserMenu } from '@t3n/components';
declare const meta: Meta<typeof UserMenu>;
export default meta;
type Story = StoryObj<typeof UserMenu>;
export declare const userMenu: Story;
export declare const active: Story;
export declare const light: Story;
export declare const notLoggedIn: Story;
export declare const extraContent: Story;
