import { Meta, StoryObj } from '@storybook/react';
import { LegacyNewsCard } from '@t3n/components';
declare const meta: Meta<typeof LegacyNewsCard>;
export default meta;
type Story = StoryObj<typeof LegacyNewsCard>;
export declare const feedLayout: Story;
export declare const heroLayout: Story;
export declare const topNews: Story;
export declare const compact: Story;
export declare const loadingFeed: Story;
export declare const loadingHero: Story;
export declare const loadingCompact: Story;
